Unsigned int tokenizer and srun args
huggingface/datatrove pull request #154
Opened 2024-04-15 06:37 UTC by marianna13

Two suggestions:

1. Change unsigned short to to unsigned int in `struct.pack` [here](https://github.com/huggingface/datatrove/blob/209ebec293cb2407c8e6fc691bfeb358ba030b09/src/datatrove/pipeline/tokens/tokenizer.py#L153) because for me short didn't work with some tokenizers (e.g. [stablelm tokenizer](https://huggingface.co/stabilityai/stablelm-2-1_6b/tree/main)).
2. Add `srun_args` varibale to slurm executor. Sometimes I need to pass some additional args to srun due to specific cluster configurations (e.g. `kill-on-bad-exit`).

Thanks!

2024-04-15 07:34 UTC, guipenedo requested changes

2024-04-15 07:34 UTC, guipenedo commented on src/datatrove/pipeline/tokens/tokenizer.py
> -        self.write_bytes(struct.pack("<%sH" % len(tokens), *tokens))
This has to be made optional (with the default being uint16 as before). There are also other changes required (size computations using "2" and the tokenizer merger, for example).

2024-04-15 07:34 UTC, guipenedo commented on src/datatrove/executor/slurm.py
> +        srun_args: dict = {},
Convention is usually to pass a sentinel value (None) as default instead of a mutable object

2024-04-17 03:21 UTC, marianna13 commented
Thanks for comments! I did this trick with computing nu,ber of bytes and tokens type (so if maximum value of tokens is more then 2**16 so too big for uint16 we will use uint32 and 4 bytes per token consequently). I don't really like my implementation (I think there's a way to make it cleaner). But conceptually I guess this is what you meant. Please let me know your thoughts!

2024-04-24 14:07 UTC, guipenedo commented
Hi! sorry for the late reply. I actually forgot you were working on uint32 tokenization and ended up implementing it myself on #160 as we needed it for an internal project at HF, is it ok with you if we change the PR to only include the srun_args change? I can also add you as a co-author of #160 if you'd like :)

2024-05-07 13:16 UTC, guipenedo approved these changes

2024-05-07 13:24 UTC, guipenedo commented
I've kept only the srun args changes as the rest has already been added to tokenizers :)

2024-05-07 13:24 UTC, merged